### PR TITLE
Capstone

### PR DESCRIPTION
**Pull request by Frederick-Ye**
In this pull request, I've implemented the following.

1. Personalize the content of the page that is different than the one in the original design
2. Follow these design guidelines, including Colors,Typography, and Layout
3. Use Bootstrap
4. Build a home and about page
5. Use media queries for 2 different screen sizes: Mobile: up to 768px wide.
 Desktop: 768px or wider.
6. Link home page and about page
7. Add a link to the home page in the header links logo
8. Add the following interactions, When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
 Add a close (X) button that closes the menu.
9. Add the section "Featured speakers" dynamically using Javascript
Store the data about the speakers in an array and data for each speaker in an object.

### CODE REVIEW

**Review by K0ppai — CHANGES_REQUESTED** [review]
# Status: Changes Required♻️♻️♻️


# Hi @Frederick-Ye  👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏 👏 
- All linter are passing ✔
- Your project is fully responsive ✔️ 
- "Featured speakers" created dynamically in JavaScript ✔️ 

## Required Changes ♻️

Please check the following messages for the required changes and all changes must be made in both desktop and mobile versions.

1. Kindly add an overlay for the background to enhance visibility of the text you can take reference in the given photo below and you can change the color of the overlay according to your preference.

#### Your Design: 
image

#### Reference: 
image


2. Please follow the design layout guidelines in the main program section in desktop version. 

Your main program section: 

image
Design guidelines: 

image

3. Kindly add background images for the speakers.

Your design:

image

Design guideline:

image


4. In the footer section for both about and main page, it would be better if you use white text and border to create the logo for a professional look. In the provided design, the background is white and the texts are black. If you're changing the background color to gray, you can use white texts and border to align with the design guidelines.

Your design: 

image

Design guideline:

image

5. Kindly add background image for the header section in the about page as provided in the design guideline.

Your design:

image


Design guideline:

image

6. Please add texts and overlay for the past summits section

Your design:

image

Design guideline:

image

7. The texts in the photo below should have a solid background color instead of being transparent according to the design guidelines for better UI. 

Your design:

image

Design guideline:

image

## Optional but Strong Suggestions 💯 

- I strongly suggest you follow the following [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) according to the project requirements, including:
    - Colors.
    - Layout: composition and space between elements.
    - The pages should look almost **identical** to the original design. Small adjustments like **text** or **image** changes are acceptable.
- For the pull request descriptions, it'd be better if you use grammatically correct format to mention the tasks you did in the pull request and bullet points for better clarifications. I recommend using [Grammarly](https://www.grammarly.com/). For your reference, you can check out the [pull request description](https://github.com/K0ppai/first-capstone-project/pull/3) of my capstone project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by Frederick-Ye** [comment]
Dear bro @K0ppai. Thanks for taking the time to review my project. I make changes according to your recommendations and guidelines. Pls check again and let me know other requirements or recommendations.

**Review by K0ppai — CHANGES_REQUESTED** [review]
# Status: Changes Required♻️♻️♻️


# Hi @Frederick-Ye  👋, 

That's a big improvement in the UI design! 💯  You did great. 👏
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏 👏 
- Added overlays to increase visibility of the texts ✔
- Professional pull request descriptions ✔️ 
- Fixed main program layouts ✔️ 

## Required Changes ♻️

Please check the following messages for the required changes and all changes must be made in both desktop and mobile versions.

1. Let's keep the padding for each section the same for neat and tidy UI as described in the attached photo below.

Design guidelines:

image

2. For the color usages in the design, you can choose primary and secondary colors instead of multiple colors background in the same page. You can check out how the original designer used colors for the background below. The same goes for the texts. If you're using blue as your original color, you should change the orange texts to blue. Kindly fix them to have color consistency in your design.

Your design:

image

Design guidelines:

image

3. I just saw that you forgot to add the part described below in the navbar. 

Your design:

image

Design guidelines:

image

4. Kindly fix the layout of the footer to match the design guidelines, the spacing between elements, font sizes and font weights. You should fix them in both about and home pages.

Your design:

image

Design guidelines:

image

5. I think you forgot to add the overlay in the header section of the about page. Currently add them to improve visibility. You can style the same as you did for the home page. It looks great! 🔥 

Your design:

image

6. As mentioned above, kindly fix the color as the design guidelines.

Your design:

image

Design guidelines:

image

7. Kindly stick to the colors for the design guidelines for the partner section in the about page for the mobile version.

Your design:

image

Design guidelines:

image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by Frederick-Ye** [comment]
@K0ppai Thanks for the detailed review brother🤩. I fixed the requirements you mentioned. The color part also does not satisfy me but this is the best i can do😂. Will do better in future projects. 🙌

**Review by soesandarwin2201 — CHANGES_REQUESTED** [review]
#
Hi @Frederick-Ye , 

Good job Making Changes and It improved a lot.
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights
✔️ GitHub Flow observed
✔️ Descriptive PR
✔️ Linters are passing
✔️ mobile responsive


## Required changes ♻️ 
  _Check the comments under the review._

## Optional suggestions
These are not mandatory but suggestions that would help improve your project
You can also consider:

- [ ] adding the animation or transition to mobile navbar 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


In Design Guideline, 
Screenshot (471)

In Your project , 
Screenshot (470)

- [ ] Please Change the font size and make sure it take the fullwidth like in the design . 

Screenshot (469)

- [ ] Please Change the view height and fontSize of the about page.

Otherwise, your project is complete and it is amazing how you improved in short time.

**Comment by Frederick-Ye** [comment]
Thanks for the review Nyi ma @soesandarwin2201🤩. I believe this is the PR i used from start and didn't open a new. There might be a confusion. I fixed the requirements and make it look like the exact provided design as best as i can. For the font-size, pls view it with 375 px. Thanks for the time🤩 and sorry for the burden😁

**Review by soesandarwin2201 — APPROVED** [review]
APPROVED 🟢

Hi @Frederick-Ye , 

Your capstone project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 



## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

Cheers, good luck in the next modules and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------

**Pull request merged**
